### ISSUE TITLE
More readme detail about context of use?

### ISSUE THREAD

**Issue by iDVB** [simlu/lambda-rollbar#164]
Hey @simlu looks like an interesting code base here.
I was on the lookout for something that could help paint a picture of how we could stream our cloudwatch logs to Rollbar and came across this.

However, I'm still a bit confused as to exactly what this code of yours does?
Is it simply a wrapper to help sending messages/logs to rollbar easier?
If so, not sure what the template is for?

Any info you have on the topic would be greatly appreciated!

**Comment by simlu** [comment]
This is a rollbar wrapper for lambda functions that allows you to send logs to rollbar directly from the lambda function. This will also handle and send errors correctly to rb in most cases. However if the lambda function totally crashes (e.g. times out or runs out of memory) it won't log to rollbar. So this is only part of the picture.

When is this useful? When you have a really long running lambda function and want to log immediately to rollbar (e.g. your lambda function runs for 15 minutes and you want to log to rb as soon as events happen).

Why was this written? The lambda wrapper rollbar provides is frankly very underwhelming. So this function handles things a lot more generically, robust and is (arguably) easier to use.

Looking at this and the other tickets you opened it seems that you were looking for [lambda-monitor](https://github.com/simlu/lambda-monitor) instead. I'm going to close this ticket, but feel free to re-open it, if you have further questions. I will answer your other tickets next.
